// GENERATED — design-system/scripts/build_pixel_battle_assets.py가 만든다.
// 손으로 고치지 말 것. 원본이 바뀌면 스크립트를 다시 돌린다.

import 'dart:ui' show Size;

/// 구운 도트 자산의 native 크기. 무대는 이 값에 정수 배율을 곱해 그린다.
const expeditionPixelAssetSizes = <String, Size>{
  'assets/adventure/pixel/actors/aloof-pot.png': Size(25, 59),
  'assets/adventure/pixel/actors/baby-pot.png': Size(31, 60),
  'assets/adventure/pixel/actors/cactus.png': Size(36, 58),
  'assets/adventure/pixel/actors/gal-pot.png': Size(26, 60),
  'assets/adventure/pixel/actors/gumiho-pot.png': Size(41, 60),
  'assets/adventure/pixel/actors/handsome-pot.png': Size(28, 60),
  'assets/adventure/pixel/actors/maestro-pot.png': Size(38, 59),
  'assets/adventure/pixel/actors/magical-pot.png': Size(37, 58),
  'assets/adventure/pixel/actors/marten-pot.png': Size(56, 60),
  'assets/adventure/pixel/actors/ninja-pot.png': Size(52, 60),
  'assets/adventure/pixel/actors/nurse-pot.png': Size(30, 59),
  'assets/adventure/pixel/actors/pretty-pot.png': Size(31, 59),
  'assets/adventure/pixel/actors/restorer-pot.png': Size(27, 58),
  'assets/adventure/pixel/actors/student-pot.png': Size(24, 58),
  'assets/adventure/pixel/actors/sunflower.png': Size(36, 59),
  'assets/adventure/pixel/actors/tsundere-pot.png': Size(23, 59),
  'assets/adventure/pixel/actors/zombie-pot.png': Size(35, 60),
  'assets/adventure/pixel/backdrops/echo_well-landscape.png': Size(384, 256),
  'assets/adventure/pixel/backdrops/echo_well-portrait.png': Size(256, 384),
  'assets/adventure/pixel/backdrops/heartwood_observatory-landscape.png': Size(384, 256),
  'assets/adventure/pixel/backdrops/heartwood_observatory-portrait.png': Size(256, 384),
  'assets/adventure/pixel/backdrops/moss_archive-landscape.png': Size(384, 256),
  'assets/adventure/pixel/backdrops/moss_archive-portrait.png': Size(256, 384),
  'assets/adventure/pixel/backdrops/starlight_seed_vault-landscape.png': Size(384, 256),
  'assets/adventure/pixel/backdrops/starlight_seed_vault-portrait.png': Size(256, 384),
  'assets/adventure/pixel/banners/patrol-garden-path.png': Size(512, 341),
  'assets/adventure/pixel/keepers/echo_keeper.png': Size(105, 75),
  'assets/adventure/pixel/keepers/ledger_keeper.png': Size(103, 77),
  'assets/adventure/pixel/keepers/record_keeper.png': Size(55, 76),
  'assets/adventure/pixel/keepers/seed_keeper.png': Size(75, 77),
  'assets/adventure/pixel/scenes/echo_well__dungeon_gate.png': Size(512, 341),
  'assets/adventure/pixel/scenes/echo_well__echo_well.png': Size(512, 341),
  'assets/adventure/pixel/scenes/echo_well__flooded_cave.png': Size(512, 341),
  'assets/adventure/pixel/scenes/echo_well__monster_den.png': Size(512, 341),
  'assets/adventure/pixel/scenes/echo_well__root_tunnel.png': Size(512, 341),
  'assets/adventure/pixel/scenes/echo_well__treasure_vault.png': Size(512, 341),
  'assets/adventure/pixel/scenes/heartwood_observatory__dungeon_gate.png': Size(512, 341),
  'assets/adventure/pixel/scenes/heartwood_observatory__monster_den.png': Size(512, 341),
  'assets/adventure/pixel/scenes/heartwood_observatory__moon_tower.png': Size(512, 341),
  'assets/adventure/pixel/scenes/heartwood_observatory__root_tunnel.png': Size(512, 341),
  'assets/adventure/pixel/scenes/moss_archive__dungeon_gate.png': Size(512, 341),
  'assets/adventure/pixel/scenes/moss_archive__echo_well.png': Size(512, 341),
  'assets/adventure/pixel/scenes/moss_archive__flooded_cave.png': Size(512, 341),
  'assets/adventure/pixel/scenes/moss_archive__monster_den.png': Size(512, 341),
  'assets/adventure/pixel/scenes/moss_archive__moon_tower.png': Size(512, 341),
  'assets/adventure/pixel/scenes/moss_archive__root_tunnel.png': Size(512, 341),
  'assets/adventure/pixel/scenes/moss_archive__treasure_vault.png': Size(512, 341),
  'assets/adventure/pixel/scenes/starlight_seed_vault__dungeon_gate.png': Size(512, 341),
  'assets/adventure/pixel/scenes/starlight_seed_vault__monster_den.png': Size(512, 341),
  'assets/adventure/pixel/scenes/starlight_seed_vault__root_tunnel.png': Size(512, 341),
  'assets/adventure/pixel/scenes/starlight_seed_vault__treasure_vault.png': Size(512, 341),
  'assets/adventure/pixel/tangles/backwound_clockspring.png': Size(41, 74),
  'assets/adventure/pixel/tangles/bell_knot_swirl.png': Size(73, 76),
  'assets/adventure/pixel/tangles/drifting_pressings.png': Size(67, 59),
  'assets/adventure/pixel/tangles/knotted_echo.png': Size(57, 58),
  'assets/adventure/pixel/tangles/matted_observatory.png': Size(76, 74),
  'assets/adventure/pixel/tangles/ring_shard_tangle.png': Size(59, 58),
  'assets/adventure/pixel/tangles/rolling_seedbox.png': Size(63, 58),
  'assets/adventure/pixel/tangles/scattered_records.png': Size(59, 57),
  'assets/adventure/pixel/tangles/shelf_snarl.png': Size(68, 72),
  'assets/adventure/pixel/tangles/snarled_stardust.png': Size(63, 59),
  'assets/adventure/pixel/tangles/splashing_droplets.png': Size(67, 57),
  'assets/adventure/pixel/tangles/tangled_ledger.png': Size(62, 59),
};
