// GENERATED FILE. 수정하지 말고 manifest와 생성 스크립트를 고쳐 주세요.
// design-system/scripts/build_signature_audio_map.py
part of 'expedition_signature_audio.dart';

/// 품종 고유기와 여섯 성장결 스킬의 전용 소리.
const Map<String, String> expeditionSkillSignatureAssets = {
  'absolute_zero_read': 'adventure/sfx/skill-aloof-pot-absolute-zero-read.wav',
  'archive_lantern': 'adventure/sfx/skill-archive_guide-archive-lantern.wav',
  'archive_seal': 'adventure/sfx/skill-archive_guide-archive-seal.wav',
  'blazing_counter': 'adventure/sfx/skill-tsundere-pot-blazing-counter.wav',
  'command_blade': 'adventure/sfx/skill-handsome-pot-command-blade.wav',
  'command_crescendo': 'adventure/sfx/skill-handsome-pot-command-crescendo.wav',
  'den_guardian_roar': 'adventure/sfx/skill-marten-pot-den-guardian-roar.wav',
  'ember_rage_breaker': 'adventure/sfx/skill-emotion-ember-rage-breaker.wav',
  'golden_downbeat': 'adventure/sfx/skill-maestro-pot-golden-downbeat.wav',
  'golden_seam': 'adventure/sfx/skill-restorer-pot-golden-seam.wav',
  'grave_gravity': 'adventure/sfx/skill-zombie-pot-grave-gravity.wav',
  'heart_moon_charm': 'adventure/sfx/skill-gumiho-pot-heart-moon-charm.wav',
  'heart_spotlight': 'adventure/sfx/skill-pretty-pot-heart-spotlight.wav',
  'ink_formula_burst': 'adventure/sfx/skill-student-pot-ink-formula-burst.wav',
  'iron_uppercut': 'adventure/sfx/skill-tsundere-pot-iron-uppercut.wav',
  'moonlit_lonesome_tempest': 'adventure/sfx/skill-emotion-moonlit-lonesome-tempest.wav',
  'mosaic_steel_equilibrium': 'adventure/sfx/skill-emotion-mosaic-steel-equilibrium.wav',
  'nine_tail_eclipse': 'adventure/sfx/skill-gumiho-pot-nine-tail-eclipse.wav',
  'patchwork_relay': 'adventure/sfx/skill-gal-pot-patchwork-relay.wav',
  'patina_parry': 'adventure/sfx/skill-restorer-pot-patina-parry.wav',
  'prism_meteor': 'adventure/sfx/skill-magical-pot-prism-meteor.wav',
  'rainy_frozen_tide': 'adventure/sfx/skill-emotion-rainy-frozen-tide.wav',
  'ribbon_encore': 'adventure/sfx/skill-pretty-pot-ribbon-encore.wav',
  'root_embrace': 'adventure/sfx/skill-baby-pot-root-embrace.wav',
  'runway_reversal': 'adventure/sfx/skill-gal-pot-runway-reversal.wav',
  'seal_rewrite': 'adventure/sfx/skill-student-pot-seal-rewrite.wav',
  'shadow_execution': 'adventure/sfx/skill-ninja-pot-shadow-execution.wav',
  'silent_coda': 'adventure/sfx/skill-maestro-pot-silent-coda.wav',
  'softpaw_rush': 'adventure/sfx/skill-marten-pot-softpaw-rush.wav',
  'sparkling_shock_wonder': 'adventure/sfx/skill-emotion-sparkling-shock-wonder.wav',
  'sprout_cheer': 'adventure/sfx/skill-baby-pot-sprout-cheer.wav',
  'steel_verdict': 'adventure/sfx/skill-aloof-pot-steel-verdict.wav',
  'sunny_radiant_heart': 'adventure/sfx/skill-emotion-sunny-radiant-heart.wav',
  'timefold_comet': 'adventure/sfx/skill-magical-pot-timefold-comet.wav',
  'triage_bloom': 'adventure/sfx/skill-nurse-pot-triage-bloom.wav',
  'undying_chain': 'adventure/sfx/skill-zombie-pot-undying-chain.wav',
  'venom_seam': 'adventure/sfx/skill-ninja-pot-venom-seam.wav',
  'white_garden_oath': 'adventure/sfx/skill-nurse-pot-white-garden-oath.wav',
};

/// 엉킴과 수호짐승이 저마다 내는 공격 소리.
const Map<String, String> expeditionEnemySignatureAssets = {
  'bell_spin': 'adventure/sfx/enemy-bell-knot-swirl-bell-spin.wav',
  'box_roll': 'adventure/sfx/enemy-rolling-seedbox-box-roll.wav',
  'catalogue_rain': 'adventure/sfx/enemy-shelf-snarl-catalogue-rain.wav',
  'deep_toll': 'adventure/sfx/enemy-bell-knot-swirl-deep-toll.wav',
  'drown_peal': 'adventure/sfx/guardian-bell-ringer-drown-peal.wav',
  'dust_flare': 'adventure/sfx/enemy-snarled-stardust-dust-flare.wav',
  'dust_lash': 'adventure/sfx/enemy-snarled-stardust-dust-lash.wav',
  'echo_ring': 'adventure/sfx/enemy-knotted-echo-echo-ring.wav',
  'escapement_grind': 'adventure/sfx/guardian-germination-clock-escapement-grind.wav',
  'final_redaction': 'adventure/sfx/guardian-ledger-keeper-final-redaction.wav',
  'frost_bite': 'adventure/sfx/guardian-germination-clock-frost-bite.wav',
  'gear_grind': 'adventure/sfx/enemy-backwound-clockspring-gear-grind.wav',
  'ink_mist': 'adventure/sfx/enemy-tangled-ledger-ink-mist.wav',
  'ledger_claw': 'adventure/sfx/guardian-ledger-keeper-ledger-claw.wav',
  'lens_focus': 'adventure/sfx/guardian-ring-watcher-lens-focus.wav',
  'lens_glare': 'adventure/sfx/enemy-matted-observatory-lens-glare.wav',
  'mainspring_lash': 'adventure/sfx/guardian-germination-clock-mainspring-lash.wav',
  'page_storm': 'adventure/sfx/enemy-scattered-records-page-storm.wav',
  'paper_cut': 'adventure/sfx/enemy-scattered-records-paper-cut.wav',
  'paper_flurry': 'adventure/sfx/enemy-tangled-ledger-paper-flurry.wav',
  'petal_dart': 'adventure/sfx/enemy-drifting-pressings-petal-dart.wav',
  'petal_gust': 'adventure/sfx/enemy-drifting-pressings-petal-gust.wav',
  'record_gale': 'adventure/sfx/guardian-ring-watcher-record-gale.wav',
  'record_wave': 'adventure/sfx/guardian-ledger-keeper-record-wave.wav',
  'ring_spin': 'adventure/sfx/enemy-ring-shard-tangle-ring-spin.wav',
  'ringread_turn': 'adventure/sfx/guardian-ring-watcher-ringread-turn.wav',
  'root_lockdown': 'adventure/sfx/guardian-ledger-keeper-root-lockdown.wav',
  'seal_crush': 'adventure/sfx/guardian-ledger-keeper-seal-crush.wav',
  'seed_scatter': 'adventure/sfx/enemy-rolling-seedbox-seed-scatter.wav',
  'shard_scatter': 'adventure/sfx/enemy-ring-shard-tangle-shard-scatter.wav',
  'sharp_note': 'adventure/sfx/enemy-knotted-echo-sharp-note.wav',
  'shelf_sweep': 'adventure/sfx/enemy-shelf-snarl-shelf-sweep.wav',
  'splash_wave': 'adventure/sfx/enemy-splashing-droplets-splash-wave.wav',
  'spring_snap': 'adventure/sfx/enemy-backwound-clockspring-spring-snap.wav',
  'tape_whip': 'adventure/sfx/enemy-matted-observatory-tape-whip.wav',
  'toll_sweep': 'adventure/sfx/guardian-bell-ringer-toll-sweep.wav',
  'undertow': 'adventure/sfx/guardian-bell-ringer-undertow.wav',
  'water_pop': 'adventure/sfx/enemy-splashing-droplets-water-pop.wav',
};
